import './global.css';
import '../assets/app.scss';
import { StyledComponentsRegistry } from './registry';

import Footer from '../src/components/footer';
import Header from '../src/components/header';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>

        <div style={{ minHeight: '60vh' }}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </div>

        <Footer></Footer>
      </body>
    </html>
  );
}
